/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2024-11-12 06:46:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:split", org.apache.taglibs.standard.functions.Functions.class, "split", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/spring_works/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/comunity/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725514167351L));
    _jspx_dependants.put("jar:file:/C:/spring_works/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/comunity/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/comunity/res/css/jquery-ui.min.css\" />\r\n");
      out.write("<script src=\"/comunity/res/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  $(function(){\r\n");
      out.write("	 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${script}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("	 \r\n");
      out.write("	 $(\".mkbbsbtn\").click(function(){\r\n");
      out.write("		 const bbstitle = $(\"input[name='mkbbstitle']\").val();\r\n");
      out.write("		 if(bbstitle == '') {\r\n");
      out.write("			 alert(\"커뮤니티 이름을 입력하세요.\");\r\n");
      out.write("			 $(\"input[name='mkbbstitle']\").focus();\r\n");
      out.write("			 return;\r\n");
      out.write("		 }\r\n");
      out.write("		 $.post('/comunity/admin/mkbbs?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&bbstitle='+bbstitle, \r\n");
      out.write("				 function(data) {\r\n");
      out.write("			         if(data){\r\n");
      out.write("			    	     alert(\"등록되었습니다.\");\r\n");
      out.write("			    	     document.location.reload(true);\r\n");
      out.write("			         }else{\r\n");
      out.write("			    	     alert(\"문제가 발생했습니다.\");\r\n");
      out.write("			    	     return;\r\n");
      out.write("			         } \r\n");
      out.write("		 });\r\n");
      out.write("	 });\r\n");
      out.write("	 \r\n");
      out.write("	 $(\"button[id^='edit']\").click(function(){\r\n");
      out.write("		const tr = $(this).closest(\"tr\");\r\n");
      out.write("        const id = tr.find(\"input[name='id']\").val();\r\n");
      out.write("		const bbstitle = tr.find(\"input[name='bbstitle']\").val();\r\n");
      out.write("        const skin = tr.find(\"select[name='skin']\").val();\r\n");
      out.write("		const category = tr.find(\"select[name='category']\").val();\r\n");
      out.write("        const listcount = tr.find(\"input[name='listcount']\").val();\r\n");
      out.write("		const pagecount = tr.find(\"input[name='pagecount']\").val();\r\n");
      out.write("        const lgrade = tr.find(\"select[name='lgrade']\").val();\r\n");
      out.write("		const rgrade = tr.find(\"select[name='rgrade']\").val();\r\n");
      out.write("        const fgrade = tr.find(\"select[name='fgrade']\").val();\r\n");
      out.write("		const regrade = tr.find(\"select[name='regrade']\").val();\r\n");
      out.write("        const comgrade = tr.find(\"select[name='comgrade']\").val();\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("        	url: \"/comunity/admin/edtBbsAdmin\",\r\n");
      out.write("        	method: \"post\",\r\n");
      out.write("        	data: {\r\n");
      out.write("        		id,\r\n");
      out.write("        		bbstitle,\r\n");
      out.write("                skin,\r\n");
      out.write("                category,\r\n");
      out.write("                listcount,\r\n");
      out.write("                pagecount,\r\n");
      out.write("                lgrade,\r\n");
      out.write("                rgrade,\r\n");
      out.write("                fgrade,\r\n");
      out.write("                regrade,\r\n");
      out.write("                comgrade,\r\n");
      out.write("                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("        	},\r\n");
      out.write("        	success: function(res){\r\n");
      out.write("        		if(res == 1) {\r\n");
      out.write("        			alert(\"수정이 완료되었습니다.\");\r\n");
      out.write("        		}else{\r\n");
      out.write("        			alert(\"문제가 발생했습니다. 다시 시도하세요.\");       		    \r\n");
      out.write("        		}\r\n");
      out.write("    			location.reload(true);\r\n");
      out.write("        	},\r\n");
      out.write("        	error: function(xhr, status, error) {\r\n");
      out.write("        		alert(\"문제가 발생했습니다. 다시 시도하세요.\" + error);     \r\n");
      out.write("        	}\r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("	 });\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	 $( \".sortable\" ).sortable();\r\n");
      out.write("	 \r\n");
      out.write("	 $(\".addCate\").click(function(){\r\n");
      out.write("		 const form = $(this).closest(\"form\");\r\n");
      out.write("		 const bbsid = form.find('input[name=\"bbsid\"]').val();\r\n");
      out.write("		 const categorytext = form.find('input[name=\"categorytext\"]').val();\r\n");
      out.write("		 const data = {\r\n");
      out.write("			   bbsid: bbsid,\r\n");
      out.write("			   categorytext : categorytext,\r\n");
      out.write("		 };\r\n");
      out.write("		 \r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			type: \"POST\",\r\n");
      out.write("			contentType: \"application/json;charset=utf-8\",\r\n");
      out.write("			url: \"/comunity/admin/addCategory?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("			data: JSON.stringify(data),\r\n");
      out.write("			success: function(res){\r\n");
      out.write("				if(res){\r\n");
      out.write("					alert(\"카테고리가 등록 되었습니다.\");\r\n");
      out.write("					//색각중 \r\n");
      out.write("					const newList = `     \r\n");
      out.write("		                  <li class=\"ui-state-default d-flex\">\r\n");
      out.write("	                        <div class=\"col-9\">  \r\n");
      out.write("	                            <input type=\"text\" name=\"categorytext[]\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categorytext }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("	                              class=\"form-control categoryList\">\r\n");
      out.write("	                            <input type=\"hidden\" name=\"bbsid[]\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryList.bbsid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("	                            <input type=\"hidden\" name=\"id[]\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryList.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />       \r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"col-3\">\r\n");
      out.write("	                           <button type=\"button\" class=\"categoryDelete btn btn-danger btn-sm delCate\">삭제</button> \r\n");
      out.write("	                        </div>        \r\n");
      out.write("	                       </li>`;\r\n");
      out.write("					$('.sortable').append(newList);\r\n");
      out.write("				}else{\r\n");
      out.write("					alert(\"문제가 발생했습니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(error){\r\n");
      out.write("				alert(\"문제가 발생했다구요!!!\");\r\n");
      out.write("			}\r\n");
      out.write("		 });\r\n");
      out.write("		 \r\n");
      out.write("	 });\r\n");
      out.write("	 \r\n");
      out.write("	 $(\".categoryDelete\").click(function(){\r\n");
      out.write("		 const deleteId = $(this).data(\"deleteid\");\r\n");
      out.write("		 if(confirm(\"정말로 삭제하시겠습니까?\")){\r\n");
      out.write("		   $.post(\"/comunity/admin/delCategory?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&id=\"+deleteId, function(data){\r\n");
      out.write("			   if(data){\r\n");
      out.write("				   alert(\"삭제되었습니다.\");\r\n");
      out.write("				   location.reload();\r\n");
      out.write("			   }else{\r\n");
      out.write("				   alert(\"문제가 발생했습니다.\");\r\n");
      out.write("			   }\r\n");
      out.write("		   })	\r\n");
      out.write("		 }\r\n");
      out.write("	 });\r\n");
      out.write("	 \r\n");
      out.write("	 $('.categoryEdit').click(function(){\r\n");
      out.write("		    const bbsId = $(this).data(\"bbsid\");\r\n");
      out.write("			let formData = [];\r\n");
      out.write("			let categorytext;\r\n");
      out.write("			let bbsid;\r\n");
      out.write("			let id;\r\n");
      out.write("			\r\n");
      out.write("			//.sortable 의 li를 루프로 돌리면서 데이터 수집\r\n");
      out.write("			$('ul.sortable#sortable_'+bbsId+' li').each(function(index){\r\n");
      out.write("				categorytext = $(this).find(\"input[name='categorytext[]']\").val();\r\n");
      out.write("				bbsid = $(this).find('input[name=\"bbsid[]\"]').val();\r\n");
      out.write("				id=$(this).find('input[name=\"id[]\"]').val();\r\n");
      out.write("				formData.push({\r\n");
      out.write("					id: id,\r\n");
      out.write("					bbsid: bbsid,\r\n");
      out.write("					categorytext: categorytext,\r\n");
      out.write("					categorynum: index + 1\r\n");
      out.write("				});\r\n");
      out.write("			});		\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("			    url: '/comunity/admin/editCategory?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("			    contentType: 'application/json;charset=UTF-8',\r\n");
      out.write("			    data: JSON.stringify(formData),\r\n");
      out.write("			    success: function(res) {\r\n");
      out.write("			    	if(res == 1) {\r\n");
      out.write("			    		alert(\"카테고리가 수정되었습니다.\");\r\n");
      out.write("			    		location.reload();\r\n");
      out.write("			    	}else{\r\n");
      out.write("			    		alert('수정 중 문제가 발생했습니다.');\r\n");
      out.write("			    	}\r\n");
      out.write("			    },\r\n");
      out.write("			    error: function(error) {\r\n");
      out.write("			    	alert(\"오류가 발생했습니다.\");\r\n");
      out.write("			    }\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		 });\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	 $(\".edtFile\").click(function(){\r\n");
      out.write("		const form = \"#edtform-\" + $(this).data(\"bbsid\");\r\n");
      out.write("        let formData = new FormData($(form)[0]);\r\n");
      out.write("        $.ajax({\r\n");
      out.write("        	url: \"/comunity/admin/editfile?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('=');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("        	type: \"post\",\r\n");
      out.write("        	data: formData,\r\n");
      out.write("        	processData: false, //FormData 필수\r\n");
      out.write("        	contentType: false, //FormData 필수\r\n");
      out.write("        	success: function(res) {\r\n");
      out.write("        		if(res == 1){\r\n");
      out.write("        		   alert(\"성공적으로 수정했습니다.\");\r\n");
      out.write("        		}else{\r\n");
      out.write("        		   alert(\"문제가 발생했습니다.\");\r\n");
      out.write("        		}   \r\n");
      out.write("        	},\r\n");
      out.write("        	error: function(xhr, status, error) {\r\n");
      out.write("        		console.error(\"xhr\"+xhr, \"status\" + status , \"error\" + error);\r\n");
      out.write("        		alert(\"문제가 발생했습니다.\");\r\n");
      out.write("        	}\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("	 });\r\n");
      out.write("	 \r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<h1 class=\"text-center mb-4\">관리자 모드</h1>\r\n");
      out.write("<table class=\"table table-striped table-hover comtable\">\r\n");
      out.write("  <thead>\r\n");
      out.write("     <tr>\r\n");
      out.write("        <th>번호</th>\r\n");
      out.write("        <th>커뮤니티이름</th>\r\n");
      out.write("        <th>스킨</th>\r\n");
      out.write("        <th>카테고리</th>\r\n");
      out.write("        <th>목록크기</th>\r\n");
      out.write("        <th>페이지크기</th>\r\n");
      out.write("        <th>보기권한</th>\r\n");
      out.write("        <th>쓰기권한</th>\r\n");
      out.write("        <th>파일</th>\r\n");
      out.write("        <th>답글</th>\r\n");
      out.write("        <th>코멘트</th>\r\n");
      out.write("        <th></th>\r\n");
      out.write("     </tr>   \r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 커뮤니티 등록 -->\r\n");
      out.write("<div class=\"modal\" id=\"mkbbs\">\r\n");
      out.write("                    <div class='modal-dialog'>\r\n");
      out.write("                       <div class=\"modal-content\" style=\"padding:30px\">\r\n");
      out.write("                      \r\n");
      out.write("                          <div class=\"modal-body text-left\"> \r\n");
      out.write("                            <form id=\"mkbbsForm\" method=\"post\">\r\n");
      out.write("                            \r\n");
      out.write("                             <label class=\"mt-2\">커뮤니티이름</label>\r\n");
      out.write("								<div class=\"input-group mb-3\"> \r\n");
      out.write("								  <input type=\"text\" \r\n");
      out.write("								         name=\"mkbbstitle\" \r\n");
      out.write("								         class=\"form-control\" \r\n");
      out.write("								         placeholder=\"커뮤니티이름\" \r\n");
      out.write("								         value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.filesize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("								         style=\"max-width:100%\">	\r\n");
      out.write("								</div> \r\n");
      out.write("                              \r\n");
      out.write("								<div class=\"text-center\">\r\n");
      out.write("								   <button type=\"button\" \r\n");
      out.write("								           class=\"mkbbsbtn btn btn-warning py-2 px-4\">생성</button> \r\n");
      out.write("						        </div> \r\n");
      out.write("						    </form>    \r\n");
      out.write("\r\n");
      out.write("                          </div>\r\n");
      out.write("                          \r\n");
      out.write("                          <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                          </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/index.jsp(222,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /WEB-INF/views/admin/index.jsp(222,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/index.jsp(222,5) '${lists }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lists }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        ");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("        ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("        ");
            if (_jspx_meth_c_005fset_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("        <tr>\r\n");
            out.write("           <td>\r\n");
            out.write("              <a href=\"bbs/list?bbsid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" target=\"_blank\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("               <input type=\"hidden\" name=\"id\" class=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("           </td> \r\n");
            out.write("           <td><input type=\"text\" name=\"bbstitle\" class=\"bbstitle\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.bbstitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /></td>\r\n");
            out.write("           <td>\r\n");
            out.write("               <select name=\"skin\" id=\"skin");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  <option value=\"bbs\">게시판형</option>\r\n");
            out.write("                  <option value=\"gallery\">갤러리형</option>\r\n");
            out.write("                  <option value=\"article\">기사형</option>\r\n");
            out.write("                  <option value=\"blog\">블로그형</option>\r\n");
            out.write("               </select>\r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"category\" id=\"category");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"0\">사용안함</option>\r\n");
            out.write("                 <option value=\"1\">사용함</option>\r\n");
            out.write("              </select>\r\n");
            out.write("              ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("              \r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <input type=\"text\" name=\"listcount\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.listcount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("           </td>  \r\n");
            out.write("           <td>\r\n");
            out.write("              <input type=\"text\" name=\"pagecount\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.pagecount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("          </td>\r\n");
            out.write("           \r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"lgrade\" id=\"lgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           </td>\r\n");
            out.write("           <td>         \r\n");
            out.write("              <select name=\"rgrade\" id=\"rgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("         \r\n");
            out.write("           </td>\r\n");
            out.write("           <td> \r\n");
            out.write("              <select name=\"fgrade\" id=\"fgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"-1\">비허용</option>\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           <!--  파일업로드가 허용이면 파일 새부설정 출력 -->   \r\n");
            out.write("           ");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("              <!--  팝업 -->   \r\n");
            out.write("              \r\n");
            out.write("              \r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"regrade\" id=\"regrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"-1\">비허용</option>\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"comgrade\" id=\"comgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"-1\">비허용</option>\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           </td>    \r\n");
            out.write("           <td>\r\n");
            out.write("           ");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("           </td>       \r\n");
            out.write("        </tr>\r\n");
            out.write("     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(223,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("dim");
      // /WEB-INF/views/admin/index.jsp(223,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/index.jsp(223,8) '${fn:split(list.thimgsize, '|') }'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_0),"${fn:split(list.thimgsize, '|') }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(224,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("fwidth");
      // /WEB-INF/views/admin/index.jsp(224,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/index.jsp(224,8) '${dim[0] }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dim[0] }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(225,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("fheight");
      // /WEB-INF/views/admin/index.jsp(225,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/index.jsp(225,8) '${dim[1] }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dim[1] }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(245,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.category == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                 <br />\r\n");
          out.write("                 <a href=\"javascript:void(0)\" data-toggle=\"modal\" data-target=\"#cate-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">카테고리관리</a>\r\n");
          out.write("                 \r\n");
          out.write("                 <div class=\"modal\" id=\"cate-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                    <div class='modal-dialog'>\r\n");
          out.write("                       <div class=\"modal-content\" style=\"padding:30px\">\r\n");
          out.write("                      \r\n");
          out.write("                          <div class=\"modal-body\"> \r\n");
          out.write("                            <form>\r\n");
          out.write("                             <input type=\"hidden\" name=\"bbsid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("								<div class=\"input-group mb-3\">\r\n");
          out.write("								  <input type=\"text\" \r\n");
          out.write("								         name=\"categorytext\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"카테고리 이름\" \r\n");
          out.write("								         style=\"max-width:100%\">\r\n");
          out.write("								  <div class=\"input-group-append\">\r\n");
          out.write("								     <button class=\"btn btn-danger\" type=\"reset\">Cancel</button>\r\n");
          out.write("								     <button class=\"btn btn-primary addCate\" type=\"button\">카테고리등록</button>\r\n");
          out.write("								  </div>\r\n");
          out.write("								</div> \r\n");
          out.write("						    </form>\r\n");
          out.write("						    \r\n");
          out.write("						    <form name=\"edtform\" action=\"/comuinity/editCategory\" id=\"edtform_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bbsid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" method=\"post\">					        \r\n");
          out.write("<ul class=\"sortable\" id=\"sortable_");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write(" ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("  \r\n");
          out.write("</ul>\r\n");
          out.write("       <button type=\"button\" data-bbsid=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"categoryEdit btn btn-warning btn-sm\">수정</button> \r\n");
          out.write("       \r\n");
          out.write("						    </form>\r\n");
          out.write("                          </div>\r\n");
          out.write("                          \r\n");
          out.write("                          <div class=\"modal-footer\">\r\n");
          out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
          out.write("                          </div>\r\n");
          out.write("                       </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                 </div>\r\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/admin/index.jsp(271,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty list.bbsCategory }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/admin/index.jsp(272,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/index.jsp(272,2) '${list.bbsCategory}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list.bbsCategory}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/admin/index.jsp(272,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("categoryList");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("     <li class=\"ui-state-default d-flex\">\r\n");
            out.write("       <div class=\"col-9\">  \r\n");
            out.write("        <input type=\"text\" name=\"categorytext[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryList.categorytext }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("               class=\"form-control categoryList\">\r\n");
            out.write("        <input type=\"hidden\" name=\"bbsid[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryList.bbsid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("        <input type=\"hidden\" name=\"id[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryList.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />       \r\n");
            out.write("       </div>\r\n");
            out.write("       <div class=\"col-3\">\r\n");
            out.write("          <button type=\"button\" data-deleteid=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryList.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"categoryDelete btn btn-danger btn-sm\">삭제</button> \r\n");
            out.write("       </div>        \r\n");
            out.write("     </li>\r\n");
            out.write("  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(337,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.fgrade >= 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                 <br />\r\n");
          out.write("                 <a href=\"javascript:void(0)\" data-toggle=\"modal\" data-target=\"#file-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">업로드설정</a>\r\n");
          out.write("                 \r\n");
          out.write("                 <div class=\"modal\" id=\"file-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                    <div class='modal-dialog'>\r\n");
          out.write("                       <div class=\"modal-content\" style=\"padding:30px\">\r\n");
          out.write("                      \r\n");
          out.write("                          <div class=\"modal-body text-left\"> \r\n");
          out.write("                            <form id=\"edtform-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" method=\"post\">\r\n");
          out.write("                             <p class=\"text-danger\">*단위: M(메가바이트), 확장자는 쉼표로 구분</p>\r\n");
          out.write("                             <label class=\"mt-2\">파일최대크기</label>\r\n");
          out.write("                             <input type=\"hidden\" name=\"bbsid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("								<div class=\"input-group mb-3\"> \r\n");
          out.write("								  <input type=\"text\" \r\n");
          out.write("								         name=\"filesize\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"파일최대크기(단위:M)\" \r\n");
          out.write("								         value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.filesize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								         style=\"max-width:100%\">	\r\n");
          out.write("								</div> \r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                                <label class=\"mt-2\">전체파일최대크기</label>\r\n");
          out.write(" 								<div class=\"input-group mb-3\">\r\n");
          out.write("								  <input type=\"text\" \r\n");
          out.write("								         name=\"allfilesize\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"전체 파일최대크기(단위:M)\" \r\n");
          out.write("								         value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.allfilesize }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								         style=\"max-width:100%\">\r\n");
          out.write("								</div> \r\n");
          out.write("								\r\n");
          out.write("								<label class=\"mt-2\">확장자제한(쉼표로구분)</label>\r\n");
          out.write("								<div class=\"input-group mb-3\">\r\n");
          out.write("								  <input type=\"text\" \r\n");
          out.write("								         name=\"filechar\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"확장자제한(쉼표로 구분)\" \r\n");
          out.write("								         value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.filechar }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								         style=\"max-width:100%\">\r\n");
          out.write("								</div> \r\n");
          out.write("								<label class=\"mt-2\">이미지썸네일크기(단위px, 가로, 세로 순), 가로 또는 세로 둘 중 하나만 적으면 비율로 적용됨</label>\r\n");
          out.write("								<div class=\"input-group mb-3\">\r\n");
          out.write("								    <input type=\"text\" \r\n");
          out.write("								         name=\"fwidth\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"가로(px)\" \r\n");
          out.write("								         value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fwidth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								         style=\"max-width:50%\">\r\n");
          out.write("								     <input type=\"text\" \r\n");
          out.write("								         name=\"fheight\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"세로(px)\" \r\n");
          out.write("								         value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fheight }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								         style=\"max-width:50%\">    \r\n");
          out.write("								</div>\r\n");
          out.write("								<div class=\"text-center\">\r\n");
          out.write("								   <button type=\"button\" data-bbsid=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"edtFile btn btn-warning btn-sm\">수정</button> \r\n");
          out.write("						        </div> \r\n");
          out.write("						    </form>    \r\n");
          out.write("\r\n");
          out.write("                          </div>\r\n");
          out.write("                          \r\n");
          out.write("                          <div class=\"modal-footer\">\r\n");
          out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
          out.write("                          </div>\r\n");
          out.write("                       </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                 </div>\r\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(433,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty lists && list.id != 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("             <button type=\"button\" id=\"edit");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-warning btn-sm mr-2\">수정</button>\r\n");
          out.write("             <button type=\"button\" id=\"delete");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn btn-danger btn-sm mr-2\">삭제</button>\r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
