/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2024-10-17 08:28:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725514167351L));
    _jspx_dependants.put("jar:file:/C:/spring_works/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/comunity/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/comunity/res/css/jquery-ui.min.css\" />\r\n");
      out.write("<script src=\"/comunity/res/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  $(function(){\r\n");
      out.write("	 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${script}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("	 \r\n");
      out.write("	 $(\"button[id^='edit']\").click(function(){\r\n");
      out.write("		const tr = $(this).closest(\"tr\");\r\n");
      out.write("        const id = tr.find(\"input[name='id']\").val();\r\n");
      out.write("		const bbstitle = tr.find(\"input[name='bbstitle']\").val();\r\n");
      out.write("        const skin = tr.find(\"select[name='skin']\").val();\r\n");
      out.write("		const category = tr.find(\"select[name='category']\").val();\r\n");
      out.write("        const listcount = tr.find(\"input[name='listcount']\").val();\r\n");
      out.write("		const pagecount = tr.find(\"input[name='pagecount']\").val();\r\n");
      out.write("        const lgrade = tr.find(\"select[name='lgrade']\").val();\r\n");
      out.write("		const rgrade = tr.find(\"select[name='rgrade']\").val();\r\n");
      out.write("        const fgrade = tr.find(\"select[name='fgrade']\").val();\r\n");
      out.write("		const regrade = tr.find(\"select[name='regrade']\").val();\r\n");
      out.write("        const comgrade = tr.find(\"select[name='comgrade']\").val();\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("        	url: \"/comunity/admin/edtBbsAdmin\",\r\n");
      out.write("        	method: \"post\",\r\n");
      out.write("        	data: {\r\n");
      out.write("        		id,\r\n");
      out.write("        		bbstitle,\r\n");
      out.write("                skin,\r\n");
      out.write("                category,\r\n");
      out.write("                listcount,\r\n");
      out.write("                pagecount,\r\n");
      out.write("                lgrade,\r\n");
      out.write("                rgrade,\r\n");
      out.write("                fgrade,\r\n");
      out.write("                regrade,\r\n");
      out.write("                comgrade,\r\n");
      out.write("                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("        	},\r\n");
      out.write("        	success: function(res){\r\n");
      out.write("        		if(res == 1) {\r\n");
      out.write("        			alert(\"수정이 완료되었습니다.\");\r\n");
      out.write("        		}else{\r\n");
      out.write("        			alert(\"문제가 발생했습니다. 다시 시도하세요.\");       		    \r\n");
      out.write("        		}\r\n");
      out.write("    			location.reload(true);\r\n");
      out.write("        	},\r\n");
      out.write("        	error: function(xhr, status, error) {\r\n");
      out.write("        		alert(\"문제가 발생했습니다. 다시 시도하세요.\" + error);     \r\n");
      out.write("        	}\r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("	 });\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	 $( \".sortable\" ).sortable();\r\n");
      out.write("	 \r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<h1 class=\"text-center mb-4\">관리자 모드</h1>\r\n");
      out.write("<table class=\"table table-striped table-hover comtable\">\r\n");
      out.write("  <thead>\r\n");
      out.write("     <tr>\r\n");
      out.write("        <th>번호</th>\r\n");
      out.write("        <th>커뮤니티이름</th>\r\n");
      out.write("        <th>스킨</th>\r\n");
      out.write("        <th>카테고리</th>\r\n");
      out.write("        <th>목록크기</th>\r\n");
      out.write("        <th>페이지크기</th>\r\n");
      out.write("        <th>보기권한</th>\r\n");
      out.write("        <th>쓰기권한</th>\r\n");
      out.write("        <th>파일</th>\r\n");
      out.write("        <th>답글</th>\r\n");
      out.write("        <th>코멘트</th>\r\n");
      out.write("        <th></th>\r\n");
      out.write("     </tr>   \r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/index.jsp(80,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /WEB-INF/views/admin/index.jsp(80,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/index.jsp(80,5) '${lists }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lists }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        <tr>\r\n");
            out.write("           <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("               <input type=\"hidden\" name=\"id\" class=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("           </td> \r\n");
            out.write("           <td><input type=\"text\" name=\"bbstitle\" class=\"bbstitle\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.bbstitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /></td>\r\n");
            out.write("           <td>\r\n");
            out.write("               <select name=\"skin\" id=\"skin");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  <option value=\"bbs\">게시판형</option>\r\n");
            out.write("                  <option value=\"gallery\">갤러리형</option>\r\n");
            out.write("                  <option value=\"article\">기사형</option>\r\n");
            out.write("                  <option value=\"blog\">블로그형</option>\r\n");
            out.write("               </select>\r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"category\" id=\"category");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"0\">사용안함</option>\r\n");
            out.write("                 <option value=\"1\">사용함</option>\r\n");
            out.write("              </select>\r\n");
            out.write("              ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("              \r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <input type=\"text\" name=\"listcount\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.listcount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("           </td>  \r\n");
            out.write("           <td>\r\n");
            out.write("              <input type=\"text\" name=\"pagecount\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.pagecount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("          </td>\r\n");
            out.write("           \r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"lgrade\" id=\"lgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           </td>\r\n");
            out.write("           <td>         \r\n");
            out.write("              <select name=\"rgrade\" id=\"rgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("         \r\n");
            out.write("           </td>\r\n");
            out.write("           <td> \r\n");
            out.write("              <select name=\"fgrade\" id=\"fgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"-1\">비허용</option>\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select></td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"regrade\" id=\"regrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"-1\">비허용</option>\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           </td>\r\n");
            out.write("           <td>\r\n");
            out.write("              <select name=\"comgrade\" id=\"comgrade");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                 <option value=\"-1\">비허용</option>\r\n");
            out.write("                 <option value=\"0\">허용</option>\r\n");
            out.write("                 <option value=\"1\">회원(1)</option>\r\n");
            out.write("                 <option value=\"2\">회원(2)</option>\r\n");
            out.write("                 <option value=\"3\">회원(3)</option>\r\n");
            out.write("                 <option value=\"99\">관리자</option>\r\n");
            out.write("              </select>\r\n");
            out.write("           </td>    \r\n");
            out.write("           <td>\r\n");
            out.write("             <button type=\"button\" id=\"edit");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-warning btn-sm mr-2\">수정</button>\r\n");
            out.write("             \r\n");
            out.write("             <button type=\"button\" id=\"delete");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-danger btn-sm mr-2\">삭제</button>\r\n");
            out.write("           \r\n");
            out.write("           </td>       \r\n");
            out.write("        </tr>\r\n");
            out.write("     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/index.jsp(99,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.category == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                 <br />\r\n");
          out.write("                 <a href=\"javascript:void(0)\" data-toggle=\"modal\" data-target=\"#cate-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">카테고리관리</a>\r\n");
          out.write("                 \r\n");
          out.write("                 <div class=\"modal\" id=\"cate-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                    <div class='modal-dialog'>\r\n");
          out.write("                       <div class=\"modal-content\" style=\"padding:30px\">\r\n");
          out.write("                      \r\n");
          out.write("                          <div class=\"modal-body\"> \r\n");
          out.write("                            <form>\r\n");
          out.write("                             <input type=\"hidden\" name=\"bbsid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("								<div class=\"input-group mb-3\">\r\n");
          out.write("								  <input type=\"text\" \r\n");
          out.write("								         name=\"categorytext\" \r\n");
          out.write("								         class=\"form-control\" \r\n");
          out.write("								         placeholder=\"카테고리 이름\" \r\n");
          out.write("								         style=\"max-width:100%\">\r\n");
          out.write("								  <div class=\"input-group-append\">\r\n");
          out.write("								     <button class=\"btn btn-danger\" type=\"reset\">Cancel</button>\r\n");
          out.write("								     <button class=\"btn btn-primary\" type=\"button\">카테고리등록</button>\r\n");
          out.write("								  </div>\r\n");
          out.write("								</div> \r\n");
          out.write("						    </form>\r\n");
          out.write("						    \r\n");
          out.write("						    <form>\r\n");
          out.write("						       <input type=\"hidden\" name=\"bbsid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("						        \r\n");
          out.write("									<ul class=\"sortable\">\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 1</li>\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 2</li>\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 3</li>\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 4</li>\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 5</li>\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 6</li>\r\n");
          out.write("									  <li class=\"ui-state-default\"><span class=\"ui-icon ui-icon-arrowthick-2-n-s\"></span>Item 7</li>\r\n");
          out.write("									</ul>\r\n");
          out.write("						    </form>\r\n");
          out.write("                          </div>\r\n");
          out.write("                          \r\n");
          out.write("                          <div class=\"modal-footer\">\r\n");
          out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
          out.write("                          </div>\r\n");
          out.write("                       </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                 </div>\r\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
